const data = {
  good: [
    {
      id: 0,
      title: "goods1"
    }, {
      id: 1,
      title: "goods1"
    }, {
      id: 2,
      title: "goods1"
    }, {
      id: 3,
      title: "goods1"
    }, {
      id: 4,
      title: "goods1"
    }, {
      id: 5,
      title: "goods1"
    }, {
      id: 6,
      title: "goods1"
    }, {
      id: 7,
      title: "goods1"
    }, {
      id: 8,
      title: "goods1"
    }, {
      id: 9,
      title: "goods1"
    }, {
      id: 10,
      title: "goods1"
    }, {
      id: 11,
      title: "goods1"
    }, {
      id: 12,
      title: "goods1"
    }, {
      id: 13,
      title: "goods1"
    }, {
      id: 14,
      title: "goods1"
    }, {
      id: 15,
      title: "goods1"
    }, {
      id: 16,
      title: "goods1"
    }, {
      id: 17,
      title: "goods1"
    }, {
      id: 18,
      title: "goods1"
    }, {
      id: 19,
      title: "goods1"
    }, {
      id: 20,
      title: "goods1"
    }, {
      id: 21,
      title: "goods1"
    }, {
      id: 22,
      title: "goods1"
    }, {
      id: 23,
      title: "goods1"
    }, {
      id: 24,
      title: "goods1"
    }, {
      id: 25,
      title: "goods1"
    }, {
      id: 26,
      title: "goods1"
    }, {
      id: 27,
      title: "goods1"
    }, {
      id: 28,
      title: "goods1"
    }, {
      id: 29,
      title: "goods1"
    }, {
      id: 30,
      title: "goods1"
    }, {
      id: 31,
      title: "goods1"
    }, {
      id: 32,
      title: "goods1"
    }, {
      id: 33,
      title: "goods1"
    }, {
      id: 34,
      title: "goods1"
    }, {
      id: 35,
      title: "goods1"
    }, {
      id: 36,
      title: "goods1"
    }, {
      id: 37,
      title: "goods1"
    }, {
      id: 38,
      title: "goods1"
    }, {
      id: 39,
      title: "goods1"
    }, {
      id: 40,
      title: "goods1"
    }, {
      id: 41,
      title: "goods1"
    }, {
      id: 42,
      title: "goods1"
    }, {
      id: 43,
      title: "goods1"
    }, {
      id: 44,
      title: "goods1"
    }, {
      id: 45,
      title: "goods1"
    }, {
      id: 46,
      title: "goods1"
    }, {
      id: 47,
      title: "goods1"
    }, {
      id: 48,
      title: "goods1"
    }, {
      id: 49,
      title: "goods1"
    }, {
      id: 50,
      title: "goods1"
    }, {
      id: 51,
      title: "goods1"
    }, {
      id: 52,
      title: "goods1"
    }, {
      id: 53,
      title: "goods1"
    }, {
      id: 54,
      title: "goods1"
    }, {
      id: 55,
      title: "goods1"
    }, {
      id: 56,
      title: "goods1"
    }, {
      id: 57,
      title: "goods1"
    }, {
      id: 58,
      title: "goods1"
    }, {
      id: 59,
      title: "goods1"
    }
    
  ],
  share: [
    {
      id: 0,
      title: "share1"
    }, {
      id: 1,
      title: "share1"
    }, {
      id: 2,
      title: "share1"
    }, {
      id: 3,
      title: "share1"
    }, {
      id: 4,
      title: "share1"
    }, {
      id: 5,
      title: "share1"
    }, {
      id: 6,
      title: "share1"
    }, {
      id: 7,
      title: "share1"
    }, {
      id: 8,
      title: "share1"
    }, {
      id: 9,
      title: "share1"
    }, {
      id: 10,
      title: "share1"
    }, {
      id: 11,
      title: "share1"
    }, {
      id: 12,
      title: "share1"
    }, {
      id: 13,
      title: "share1"
    }, {
      id: 14,
      title: "share1"
    }, {
      id: 15,
      title: "share1"
    }, {
      id: 16,
      title: "share1"
    }, {
      id: 17,
      title: "share1"
    }, {
      id: 18,
      title: "share1"
    }, {
      id: 19,
      title: "share1"
    }, {
      id: 20,
      title: "share1"
    }, {
      id: 21,
      title: "share1"
    }, {
      id: 22,
      title: "share1"
    }, {
      id: 23,
      title: "share1"
    }, {
      id: 24,
      title: "share1"
    }, {
      id: 25,
      title: "share1"
    }, {
      id: 26,
      title: "share1"
    }, {
      id: 27,
      title: "share1"
    }, {
      id: 28,
      title: "share1"
    }, {
      id: 29,
      title: "share1"
    }, {
      id: 30,
      title: "share1"
    }, {
      id: 31,
      title: "share1"
    }, {
      id: 32,
      title: "share1"
    }, {
      id: 33,
      title: "share1"
    }, {
      id: 34,
      title: "share1"
    }, {
      id: 35,
      title: "share1"
    }, {
      id: 36,
      title: "share1"
    }, {
      id: 37,
      title: "share1"
    }, {
      id: 38,
      title: "share1"
    }, {
      id: 39,
      title: "share1"
    }, {
      id: 40,
      title: "share1"
    }, {
      id: 41,
      title: "share1"
    }, {
      id: 42,
      title: "share1"
    }, {
      id: 43,
      title: "share1"
    }, {
      id: 44,
      title: "share1"
    }, {
      id: 45,
      title: "share1"
    }, {
      id: 46,
      title: "share1"
    }, {
      id: 47,
      title: "share1"
    }, {
      id: 48,
      title: "share1"
    }, {
      id: 49,
      title: "share1"
    }, {
      id: 50,
      title: "share1"
    }, {
      id: 51,
      title: "share1"
    }, {
      id: 52,
      title: "share1"
    }, {
      id: 53,
      title: "share1"
    }, {
      id: 54,
      title: "share1"
    }, {
      id: 55,
      title: "share1"
    }, {
      id: 56,
      title: "share1"
    }, {
      id: 57,
      title: "share1"
    }, {
      id: 58,
      title: "share1"
    }, {
      id: 59,
      title: "share1"
    }

  ],
  ask: [
    {
      id: 0,
      title: "ask1"
    }, {
      id: 1,
      title: "ask1"
    }, {
      id: 2,
      title: "ask1"
    }, {
      id: 3,
      title: "ask1"
    }, {
      id: 4,
      title: "ask1"
    }, {
      id: 5,
      title: "ask1"
    }, {
      id: 6,
      title: "ask1"
    }, {
      id: 7,
      title: "ask1"
    }, {
      id: 8,
      title: "ask1"
    }, {
      id: 9,
      title: "ask1"
    }, {
      id: 10,
      title: "ask1"
    }, {
      id: 11,
      title: "ask1"
    }, {
      id: 12,
      title: "ask1"
    }, {
      id: 13,
      title: "ask1"
    }, {
      id: 14,
      title: "ask1"
    }, {
      id: 15,
      title: "ask1"
    }, {
      id: 16,
      title: "ask1"
    }, {
      id: 17,
      title: "ask1"
    }, {
      id: 18,
      title: "ask1"
    }, {
      id: 19,
      title: "ask1"
    }, {
      id: 20,
      title: "ask1"
    }, {
      id: 21,
      title: "ask1"
    }, {
      id: 22,
      title: "ask1"
    }, {
      id: 23,
      title: "ask1"
    }, {
      id: 24,
      title: "ask1"
    }, {
      id: 25,
      title: "ask1"
    }, {
      id: 26,
      title: "ask1"
    }, {
      id: 27,
      title: "ask1"
    }, {
      id: 28,
      title: "ask1"
    }, {
      id: 29,
      title: "ask1"
    }, {
      id: 30,
      title: "ask1"
    }, {
      id: 31,
      title: "ask1"
    }, {
      id: 32,
      title: "ask1"
    }, {
      id: 33,
      title: "ask1"
    }, {
      id: 34,
      title: "ask1"
    }, {
      id: 35,
      title: "ask1"
    }, {
      id: 36,
      title: "ask1"
    }, {
      id: 37,
      title: "ask1"
    }, {
      id: 38,
      title: "ask1"
    }, {
      id: 39,
      title: "ask1"
    }, {
      id: 40,
      title: "ask1"
    }, {
      id: 41,
      title: "ask1"
    }, {
      id: 42,
      title: "ask1"
    }, {
      id: 43,
      title: "ask1"
    }, {
      id: 44,
      title: "ask1"
    }, {
      id: 45,
      title: "ask1"
    }, {
      id: 46,
      title: "ask1"
    }, {
      id: 47,
      title: "ask1"
    }, {
      id: 48,
      title: "ask1"
    }, {
      id: 49,
      title: "ask1"
    }, {
      id: 50,
      title: "ask1"
    }, {
      id: 51,
      title: "ask1"
    }, {
      id: 52,
      title: "ask1"
    }, {
      id: 53,
      title: "ask1"
    }, {
      id: 54,
      title: "ask1"
    }, {
      id: 55,
      title: "ask1"
    }, {
      id: 56,
      title: "ask1"
    }, {
      id: 57,
      title: "ask1"
    }, {
      id: 58,
      title: "ask1"
    }, {
      id: 59,
      title: "ask1"
    }

  ],
};

export default data;